# Generated by Django 4.1.2 on 2022-10-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserFollows",),
    ]
