# Generated by Django 4.1.2 on 2022-10-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_userfollows"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="user", new_name="follows",
        ),
    ]
