# Generated by Django 4.1.2 on 2022-10-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_user_userprofile_follows"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="follows", new_name="user",
        ),
    ]
