# Generated by Django 4.1.2 on 2022-10-23 20:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0002_rename_userprofile_profile"),
    ]

    operations = [
        migrations.RenameModel(old_name="Profile", new_name="UserProfile",),
    ]
